version: "3.9"

services:
  notification-manager:
    hostname: notification-manager
    container_name: notification-manager
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    env_file:
      - .env
    networks:
      - hotdeal-service

networks:
  hotdeal-service:
    name: hotdeal-service
    external: true
