version: "3.9"

services:
  notification-manager:
    hostname: notification-manager
    container_name: notification-manager
    image: notification-manager:1.0.1
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    env_file:
      - .env
    networks:
      - hotdeal-service
      - persistence
      - monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: "promtail-notification-manager"
    hostname: "promtail-notification-manager"
    volumes:
      - ./grafana-stack/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - hotdeal-service
      - monitoring

networks:
  hotdeal-service:
    name: hotdeal-service
    external: true
  persistence:
    name: persistence
    external: true
  monitoring:
    name: monitoring
    external: true