version: "3.9"

services:
  notification-manager:
    hostname: notification-manager
    container_name: notification-manager
    image: notification-manager:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    networks:
      - hotdeal-service
      - persistence

networks:
  hotdeal-service:
    name: hotdeal-service
    external: true
  persistence:
    name: persistence
    external: true